### ISSUE TITLE
Somehow it doesn't converge for me

### ISSUE THREAD

**Issue by mgrouch** [randyaliased/KalmANF#2]
I've tried to compare it with Aranovskiy filter and I hoped to use KalmANF instead of Aranovkiy filter.
However KalmANF  doesn't converge for me in presence of a noise.

Here is my code:

````

import numpy as np
from numpy import sin, cos, sqrt, pi
import matplotlib.pyplot as plt
import adaptive_notch_filters as anf

SamplingRateHz = 250.0
WavePeriodSec = 3.0
WaveAmplitudeMeters = 0.3
WaveNumberRadPerSec = 2 * pi / WavePeriodSec
WavePhase = 0  # pi / 2.5

delta_t = 1.0 / SamplingRateHz
RunDurationSec = 60.0
iterations = round(RunDurationSec/delta_t)

noise = np.random.normal(0, 0.2, iterations)


def heave_function(time):
    return WaveAmplitudeMeters * sin(WaveNumberRadPerSec * time - WavePhase) \
      + WaveAmplitudeMeters * 0.15 * noise[round(time/delta_t)] \
      + WaveAmplitudeMeters * 0.25 * cos(3 * WaveNumberRadPerSec * time)


# initialize Aranovskiy algorithm constants
omega_up = 0.04 * (2 * pi)  # upper frequency * 2 * pi
a = omega_up
b = a
k = 200
theta_0 = - omega_up * omega_up / 4.0
x1_0 = 0.0
sigma_0 = theta_0

# initialize Aranovskiy algorithm variables
x1 = x1_0
theta = theta_0
sigma = sigma_0

chart_t = np.zeros(iterations)
chart_p = np.zeros(iterations)
y_arr = np.zeros(iterations)
#chart_p_avg = np.zeros(iterations)

t = 0.0
i = 0
while i < iterations:
    heave = heave_function(t)

    # Aranovskiy algorithm update()
    y = heave
    y_arr[i] = y
    x1_dot = - a * x1 + b * y
    sigma_dot = - k * x1 * x1 * theta - k * a * x1 * x1_dot - k * b * x1_dot * y
    theta = sigma + k * b * x1 * y
    omega = sqrt(abs(theta))
    x1 = x1 + x1_dot * delta_t
    sigma = sigma + sigma_dot * delta_t

    chart_t[i] = t
    chart_p[i] = (omega / (2 * pi))
    print(chart_p[i])

    t += delta_t
    i += 1

fs = SamplingRateHz
rho = 0.05
f_kal, a_kal, e_kal = anf.kalmanf(y_arr, fs, rho, q=0.1, r=100.0)  # KalmANF


plt.plot(chart_t, chart_p, "b-", label="Freq Aranovskiy")
plt.plot(chart_t[1000:], f_kal[1000:], "g-", label="Freq KalmANF")
#plt.plot(chart_t, y_arr, "r-", label="Y")
plt.grid()
plt.legend()
plt.show()


````
![KalmANF](https://github.com/user-attachments/assets/865cccfe-b49e-4324-9f59-0c4ad9435aa6)

What could be wrong?

Thanks

**Comment by randyaliased** [comment]
I'd suspect a few things here. It could be that the frequency you are trying to detect is quite low (close to 0 Hz). The initial guess for the frequency component is half of Nyquist, so it could be that it does not converge very well (something about that was written in the paper). You could alternatively specify a different initialization point, say 0 Hz if you know your target frequency is closer to that as opposed to Nyquist. The other thing is that at such low frequencies, the effectiveness of a notch filter is not that great, it would rather be a high pass filter (you can plot the freq. response with freqz to see how it looks). 

I made a minor modification to your code to just simplify a bit and raised the fundamental freq. by a factor of 10 and seems to do alright.

As a check to see what's going on, I'd recommend always plotting the frequency response of the notch filter and looking at the spectrogram with the result overlaid. You can tell a bit more as opposed to looking at the convergence curve alone.



import numpy as np
from numpy import sin, cos, sqrt, pi
import matplotlib.pyplot as plt
import adaptive_notch_filters as anf
from scipy import signal

SamplingRateHz = 250.0
WavePeriodSec = 0.3
WaveAmplitudeMeters = 0.3
WaveNumberRadPerSec = 2 * pi / WavePeriodSec
WavePhase = 0  # pi / 2.5

delta_t = 1.0 / SamplingRateHz
RunDurationSec = 60.0
iterations = round(RunDurationSec/delta_t)
noise = np.random.normal(0, 0.2, iterations)

def heave_function(time):
    return WaveAmplitudeMeters * sin(WaveNumberRadPerSec * time - WavePhase) \
      + WaveAmplitudeMeters * 0.25 * cos(3 * WaveNumberRadPerSec * time)

tt = np.arange(0, 60, delta_t)

x = heave_function(tt)
n = WaveAmplitudeMeters * 0.15 * noise

y = x + n

rho = 0.3
f_kal, a_kal, e_kal = anf.kalmanf(y, fs, rho, q=1e-3, r=1.0)  # KalmANF

f_sg, t_sg, Z_mag = signal.spectrogram(y, fs=SamplingRateHz,nperseg=256,window='hann',mode='magnitude')

fig, axes = plt.subplots()
sg = axes.imshow(10*np.log10(Z_mag**2), origin='lower',aspect='auto')
axes.plot(tt,f_kal,'k-',linewidth=1.2,label ='KalmANF')
axes.set_ylabel('Frequency (Hz)')
axes.set_xlabel('Time (s)')
axes.legend()


<img width="610" alt="image" src="https://github.com/user-attachments/assets/7fc97b7d-d333-461d-bbb9-6dd09a1e9730">

**Comment by mgrouch** [comment]
I see you changed WavePeriodSec = 3.0 to WavePeriodSec = 0.3 and got better results.

However I'm trying to apply this to estimating wave frequency of an ocean wave which can have even lower frequencies
(Periods up to 30 seconds)

In those cases it seems converges to a a frequency which is magnitude higher than expected result.

>  You could alternatively specify a different initialization point, say 0 Hz

How can I do that?

Thanks

**Comment by mgrouch** [comment]
I've modified the filter code to set 'a' close to 2.0 like this:


````
    a_kal[0] = 1.999999
    a_kal[1] = 1.999999
    
    p_cov = 0  # initialize covariance of the error

````

and in reset of the filter:


````

        # Compute frequency
        if (a_kal[n] > 2) or (a_kal[n] < -2):
            print('a = ' + str(a_kal[n]) + ' is out of range, resetting')
            #a_kal[n] = 0  # reset coefficient if a is out of range to compute acos
            if (a_kal[n] > 2):
                a_kal[n] = 1.999999
            else:
                a_kal[n] = -1.999999

````

And I'm getting better results ( I also changed rho, r, q )

Here is the code:


````

import numpy as np
from numpy import sin, cos, sqrt, pi
import matplotlib.pyplot as plt
import adaptive_notch_filters as anf
from scipy import signal

SamplingRateHz = 250.0
WavePeriodSec = 3.0
WaveAmplitudeMeters = 0.3
WaveNumberRadPerSec = 2 * pi / WavePeriodSec
WavePhase = 0  # pi / 2.5

delta_t = 1.0 / SamplingRateHz
RunDurationSec = 60.0
iterations = round(RunDurationSec/delta_t)
noise = np.random.normal(0, 0.2, iterations)


def heave_function(time):
    return WaveAmplitudeMeters * sin(WaveNumberRadPerSec * time - WavePhase) \
      + WaveAmplitudeMeters * 0.25 * cos(3 * WaveNumberRadPerSec * time)


tt = np.arange(0, 60, delta_t)

x = heave_function(tt)
n = WaveAmplitudeMeters * 0.15 * noise

y = x + n

rho = 0.8
f_kal, a_kal, e_kal = anf.kalmanf(y, fs=SamplingRateHz, rho=rho, q=1e-4, r=10000.0)  # KalmANF

f_sg, t_sg, Z_mag = signal.spectrogram(y, fs=SamplingRateHz, nperseg=256, window='hann', mode='magnitude')

fig, axes = plt.subplots()
#sg = axes.imshow(10*np.log10(Z_mag**2), origin='lower', aspect='auto')
axes.plot(tt[1000:], f_kal[1000:], 'k-', linewidth=1.2, label='KalmANF')
axes.set_ylabel('Frequency (Hz)')
axes.set_xlabel('Time (s)')
axes.legend()
plt.show()


````


However it still converges to 0.4 Hz when correct answer should be 0.333333333 Hz (for 3.0 sec period)

Thanks

**Comment by mgrouch** [comment]
I also have few suggestions on code implementation. Right now it's using arrays and heavy on memory.
Typically Kalman methods are used on micro-controllers as on-line filters. So only previous and next step data are kept in memory.
Also instead of fixed sample rate a Kalman step function should take delta_t for that step,
because sampling on micro-controller might not always be uniform (but close to uniform).
Also it should take more additional parameters like initial a (between -2 and 2) and how a is handled on resets (instead of setting it to 0 on reset it might take extreme forms of -2 and 2 or 
if there is an idea of what frequency should be it's

a = 2 * cos(2 * pi * f0 / fs)

Thanks,

**Comment by mgrouch** [comment]
I've done more comparisons with Aranovskiy filter

````

import numpy as np
from numpy import sin, cos, sqrt, pi
import matplotlib.pyplot as plt
import adaptive_notch_filters as anf

SamplingRateHz = 250.0
WavePeriodSec = 3.0
WaveAmplitudeMeters = 0.3
WaveNumberRadPerSec = 2 * pi / WavePeriodSec
WavePhase = 0  # pi / 2.5

delta_t = 1.0 / SamplingRateHz
RunDurationSec = 600.0
iterations = round(RunDurationSec/delta_t)

noise = np.random.normal(0, 0.2, iterations)


def heave_function(time):
    return WaveAmplitudeMeters * sin(WaveNumberRadPerSec * time - WavePhase) \
      + WaveAmplitudeMeters * 0.15 * noise[round(time/delta_t)]  \
      + WaveAmplitudeMeters * 0.25 * cos(3 * WaveNumberRadPerSec * time) #\


# initialize Aranovskiy algorithm constants
omega_up = 0.04 * (2 * pi)  # upper frequency * 2 * pi
a = omega_up
b = a
k = 50
theta_0 = - omega_up * omega_up / 4.0
x1_0 = 0.0
sigma_0 = theta_0

# initialize Aranovskiy algorithm variables
x1 = x1_0
theta = theta_0
sigma = sigma_0

chart_t = np.zeros(iterations)
chart_p = np.zeros(iterations)
y_arr = np.zeros(iterations)
#chart_p_avg = np.zeros(iterations)

t = 0.0
i = 0
while i < iterations:
    heave = heave_function(t)

    # Aranovskiy algorithm update()
    y = heave
    y_arr[i] = y
    x1_dot = - a * x1 + b * y
    sigma_dot = - k * x1 * x1 * theta - k * a * x1 * x1_dot - k * b * x1_dot * y
    theta = sigma + k * b * x1 * y
    omega = sqrt(abs(theta))
    x1 = x1 + x1_dot * delta_t
    sigma = sigma + sigma_dot * delta_t

    chart_t[i] = t
    chart_p[i] = (omega / (2 * pi))
    print(chart_p[i])

    t += delta_t
    i += 1

fs = SamplingRateHz
rho = 0.95
f_kal, a_kal, e_kal = anf.kalmanf(y_arr, fs, rho=rho, q=1e-5, r=1000000.0)  # KalmANF


plt.plot(chart_t, chart_p, "b-", label="Freq Aranovskiy")
plt.plot(chart_t, f_kal, "g-", label="Freq KalmANF")
#plt.plot(chart_t, y_arr, "r-", label="Y")
plt.grid()
plt.legend()
plt.show()

 
````

And I keep getting KalmANF converging to wrong frequency where Aranovskiy filter converges to the right one.
(That was with my previous corrections for 'a')

![KalmANF_0](https://github.com/user-attachments/assets/02aa4584-466c-4e50-aa62-9dfdef82d9b3)


It seems the presence of another higher frequency harmonic just prevents this filter from detecting main frequency
while Aranovskiy filter can just deal with it easily. On the good side your method converges faster (If no additional harmonic is present)

**Comment by mgrouch** [comment]
For 

````
def heave_function(time):
    return WaveAmplitudeMeters * sin(WaveNumberRadPerSec * time - WavePhase) \
      + WaveAmplitudeMeters * 0.15 * noise[round(time/delta_t)]  #\
      #+ WaveAmplitudeMeters * 0.25 * cos(3 * WaveNumberRadPerSec * time) #\

````

This is how it fares against Aranovskiy filter


![KalmANF_1](https://github.com/user-attachments/assets/790974ea-9e1f-464e-bbfa-5255fd52f812)

**Comment by randyaliased** [comment]
Right, this is indeed expected since the signal model assumed a single sinusoid in noise. The performance certainly degrades when this assumption is violated and also when there is lower SNR. The latter was briefly discussed in section 4.1.2 in the paper, and there's definitely scope for improving things. For multiple sinusoids, one can for instance run multiple ANFs in cascade, but the cost function becomes dirtier and a solution may involve some nonlinear algorithms. You also lose some of the pedagogic aspect of this work (i.e., a simple Kalman filter involving audio that students can implement) which was the intention more than anything. But thanks for evaluating it and for your suggestions!

**Comment by mgrouch** [comment]
Thank you for the explanation! 
It might be too much to ask from me but are there methods I could use to find fundamental frequency with fast convergence
and with presence of multiple harmonics (like in ocean waves). The filter I'm using does converge to where I need but
it converges slow and before convergence jumps really a lot.

Thanks again

**Comment by randyaliased** [comment]
You can check out the book on multi-pitch estimation - https://books.google.co.uk/books/about/Multi_pitch_Estimation.html?id=GQB79nZaR3MC&redir_esc=y
There are lots of methods and references for you to consult.

Another quick thought - for your particular scenario, your sampling frequency is quite high (250 Hz), whereas your signal of interest has a frequencies around of 0.3 Hz. You may therefore want to consider downsampling quite a bit before doing the detection. Good luck!
